name: studyquest_app
description: App educacional gamificado baseado na BNCC brasileira
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.4.0
  go_router: ^12.1.3 
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  percent_indicator: ^4.2.1
  flutter_svg: ^2.0.7
  confetti: ^0.7.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.2
  http: ^1.1.0
  json_annotation: ^4.8.1
  
  # Firebase - SEM AUTH SDK
  firebase_core: ^2.13.0
  cloud_firestore: ^4.8.0
  
  audioplayers: ^5.1.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/questoes/
    - assets/images/questoes/6ano/
    - assets/images/questoes/7ano/
    - assets/images/questoes/8ano/
    - assets/images/questoes/9ano/
    - assets/images/questoes/ensino-medio/
    - assets/images/questoes/modo_descoberta/
    
    # ========================================
    # AVATARES - Sistema 8 Avatares + 3 Estados (24 PNGs)
    # ========================================
    # Acadêmico Masculino (3 estados)
    - assets/images/avatars/academico/masculino/
    # Acadêmico Feminino (3 estados)
    - assets/images/avatars/academico/feminino/
    # Competitivo Masculino (3 estados)
    - assets/images/avatars/competitivo/masculino/
    # Competitivo Feminino (3 estados)
    - assets/images/avatars/competitivo/feminino/
    # Explorador Masculino (3 estados)
    - assets/images/avatars/explorador/masculino/
    # Explorador Feminino (3 estados)
    - assets/images/avatars/explorador/feminino/
    # Equilibrado Masculino (3 estados)
    - assets/images/avatars/equilibrado/masculino/
    # Equilibrado Feminino (3 estados)
    - assets/images/avatars/equilibrado/feminino/