// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoO3KCt32eHzcT2SxlJLfbpVlk01ynlcs',
    appId: '1:802055983068:web:5bb28b22e133effc1e8919',
    messagingSenderId: '802055983068',
    projectId: 'studyquest-app-banco',
    authDomain: 'studyquest-app-banco.firebaseapp.com',
    storageBucket: 'studyquest-app-banco.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoO3KCt32eHzcT2SxlJLfbpVlk01ynlcs',
    appId: '1:802055983068:android:ba9c3b8b4c15e1251e8919',
    messagingSenderId: '802055983068',
    projectId: 'studyquest-app-banco',
    storageBucket: 'studyquest-app-banco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoO3KCt32eHzcT2SxlJLfbpVlk01ynlcs',
    appId: '1:802055983068:ios:8f9b3c8a4c15e1251e8919',
    messagingSenderId: '802055983068',
    projectId: 'studyquest-app-banco',
    iosBundleId: 'com.studyquest.studyquestApp',
    storageBucket: 'studyquest-app-banco.firebasestorage.app',
  );
}
